environment: dev
namespace: default
kube_context: minikube

traefik:
  image: containous/traefik:v1.3.5
  imagePullPolicy: IfNotPresent
  replicas: 1

savethegalaxy:
  image: genti/savethegalaxy:v0.1
  imagePullPolicy: IfNotPresent
  replicas: 1
  domain: dev.savethegalaxy.com
