environment: prod
namespace: prod
kube_context: kube-now

traefik:
  image: containous/traefik:v1.3.5
  imagePullPolicy: IfNotPresent
  replicas: 3

savethegalaxy:
  image: genti/savethegalaxy:v0.1
  imagePullPolicy: IfNotPresent
  replicas: 4
  domain: dev.savethegalaxy.com
